name: Build deb packages

on:
  push:
    branches: [ packaging ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: deb13
            codename: trixie
            image: debian:13-slim
          - name: 25.10
            codename: questing
            image: ubuntu:25.10
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6


      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          before-build-hook: |
              sed -i "1s/(\(.*\))/(\1~${{ matrix.codename }}~${{ matrix.name }})/" debian/changelog
          buildpackage-opts: --build=binary --no-sign
          docker-image: ${{ matrix.image}}

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          path: debian/artifacts/
          name: ${{ matrix.name}}-${{ matrix.codename }}
